# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Auth\XUser:
            algorithm: bcrypt
            cost: 12

    providers:
        db_provider:
            entity:
                class: AppBundle:Auth\XUser
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                #csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /
                invalidate_session: true
            anonymous: true
