# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: XengCmsCoreBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    xeng.user_manager:
        class: Xeng\Cms\CoreBundle\Services\Auth\XUserManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@fos_user.user_manager"
    xeng.role_manager:
        class: Xeng\Cms\CoreBundle\Services\Auth\XRoleManager
        arguments:
            - "@doctrine.orm.entity_manager"
